### ISSUE TITLE
How can I apply your code with Ubuntu 18.04

### ISSUE THREAD

**Issue by Mixelon-tera** [js-john/Blackmagic-DeckLink-Opencv#1]
I want to use a Decklink mini recorder 4k to apply with OpenCV in Ubuntu but it seem your code supports only mac os. How can I apply your code on ubuntu or what I have to change in your code?
Thank you.

**Comment by js-john** [comment]
I will provide a Makefile for Ubuntu later in the project.

**Comment by Mixelon-tera** [comment]
> I will provide a Makefile for Ubuntu later in the project.

Thank you very much.

**Comment by js-john** [comment]
I made some changes in the code to adapt to linux. You can pull the latest code and try.
